package dev.lumenlang.lumen.plugin.inject.bytecode;

import dev.lumenlang.lumen.api.inject.Fakes;
import dev.lumenlang.lumen.api.inject.body.InjectableBody;
import org.jetbrains.annotations.NotNull;
import org.objectweb.asm.ClassReader;
import org.objectweb.asm.Opcodes;
import org.objectweb.asm.Type;
import org.objectweb.asm.tree.AbstractInsnNode;
import org.objectweb.asm.tree.ClassNode;
import org.objectweb.asm.tree.InsnList;
import org.objectweb.asm.tree.LabelNode;
import org.objectweb.asm.tree.LdcInsnNode;
import org.objectweb.asm.tree.LocalVariableNode;
import org.objectweb.asm.tree.MethodInsnNode;
import org.objectweb.asm.tree.MethodNode;
import org.objectweb.asm.tree.TryCatchBlockNode;
import org.objectweb.asm.tree.TypeInsnNode;

import java.io.IOException;
import java.io.InputStream;
import java.io.Serializable;
import java.lang.invoke.SerializedLambda;
import java.lang.reflect.Method;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * Extracts bytecode instructions from an {@link InjectableBody} lambda or method reference.
 *
 * <p>Locates the synthetic lambda method generated by the compiler, reads its instruction list,
 * and identifies all calls to {@link Fakes} methods that need to be replaced with real bindings.
 */
public final class BytecodeExtractor {

    private static final String FAKES_INTERNAL = Type.getInternalName(Fakes.class);
    private static final Set<String> FAKES_CLASSES = Set.of(FAKES_INTERNAL);
    private static final String FAKE_DESCRIPTOR = "(Ljava/lang/String;)";

    /**
     * Extracts the bytecode body from the given serializable lambda instance.
     *
     * @param body the serializable lambda to extract from (InjectableBody, InjectableExpression, or InjectableCondition)
     * @return the extracted body with instructions and binding metadata
     * @throws IllegalArgumentException if the lambda method cannot be found or read
     */
    public static @NotNull ExtractedBody extract(@NotNull Serializable body) {
        SerializedLambda serialized = serializeLambda(body);
        if (serialized.getCapturedArgCount() > 0) {
            throw new IllegalArgumentException("Injectable lambdas must not capture any variables (found " + serialized.getCapturedArgCount() + " captured args). Use only Fakes bindings and static state.");
        }
        String declaringClassName = serialized.getImplClass().replace('/', '.');
        String implMethodName = serialized.getImplMethodName();

        Class<?> declaringClass;
        try {
            declaringClass = Class.forName(declaringClassName, false, body.getClass().getClassLoader());
        } catch (ClassNotFoundException e) {
            throw new IllegalArgumentException("Cannot find declaring class: " + declaringClassName, e);
        }

        return buildBody(readClassNode(declaringClass), implMethodName);
    }

    /**
     * Extracts bytecode from a named static method in the given class.
     *
     * @param clazz      the class containing the method
     * @param methodName the name of the static method to extract
     * @return the extracted body
     * @throws IllegalArgumentException if the method cannot be found
     */
    public static @NotNull ExtractedBody extractMethod(@NotNull Class<?> clazz, @NotNull String methodName) {
        return buildBody(readClassNode(clazz), methodName);
    }

    private static @NotNull ExtractedBody buildBody(@NotNull ClassNode classNode, @NotNull String methodName) {
        MethodNode target = findMethod(classNode, methodName);
        Map<LabelNode, LabelNode> labelMap = buildLabelMap(target.instructions);
        return new ExtractedBody(cloneInstructions(target.instructions, labelMap), detectFakeBindings(target.instructions), cloneTryCatchBlocks(target.tryCatchBlocks, labelMap), cloneLocalVariables(target, labelMap), classNode.name, methodName, Type.getReturnType(target.desc).getDescriptor(), target.maxStack, target.maxLocals);
    }

    private static @NotNull SerializedLambda serializeLambda(@NotNull Serializable lambda) {
        try {
            Method writeReplace = lambda.getClass().getDeclaredMethod("writeReplace");
            writeReplace.setAccessible(true);
            return (SerializedLambda) writeReplace.invoke(lambda);
        } catch (Exception e) {
            throw new IllegalArgumentException("Failed to serialize lambda. Ensure InjectableBody is used as a lambda expression.", e);
        }
    }

    private static @NotNull MethodNode findMethod(@NotNull ClassNode classNode, @NotNull String methodName) {
        MethodNode found = null;
        for (MethodNode mn : classNode.methods) {
            if (mn.name.equals(methodName)) {
                if (found != null) {
                    throw new IllegalArgumentException("Overloaded methods are not supported for injection: multiple methods named '" + methodName + "' in " + classNode.name.replace('/', '.'));
                }
                found = mn;
            }
        }
        if (found == null) {
            throw new IllegalArgumentException("Method '" + methodName + "' not found in " + classNode.name.replace('/', '.'));
        }
        if ((found.access & Opcodes.ACC_STATIC) == 0) {
            throw new IllegalArgumentException("Injectable method '" + methodName + "' in " + classNode.name.replace('/', '.') + " must be static");
        }
        return found;
    }

    private static @NotNull ClassNode readClassNode(@NotNull Class<?> clazz) {
        String resourceName = clazz.getName().replace('.', '/') + ".class";
        try (InputStream is = clazz.getClassLoader().getResourceAsStream(resourceName)) {
            if (is == null) {
                throw new IllegalArgumentException("Cannot read class file for " + clazz.getName());
            }
            ClassReader reader = new ClassReader(is);
            ClassNode node = new ClassNode();
            reader.accept(node, 0);
            return node;
        } catch (IOException e) {
            throw new IllegalArgumentException("Failed to read class file for " + clazz.getName(), e);
        }
    }

    private static @NotNull List<ExtractedBody.FakeBinding> detectFakeBindings(@NotNull InsnList instructions) {
        List<ExtractedBody.FakeBinding> bindings = new ArrayList<>();
        for (AbstractInsnNode insn : instructions) {
            if (insn.getType() != AbstractInsnNode.METHOD_INSN) continue;
            MethodInsnNode methodInsn = (MethodInsnNode) insn;
            if (!isFakeCall(methodInsn)) continue;

            if (!(insn.getPrevious() instanceof LdcInsnNode ldc) || !(ldc.cst instanceof String)) {
                throw new IllegalArgumentException("Fakes." + methodInsn.name + "() call must receive a constant string argument. Dynamic binding names are not supported.");
            }
            String returnDescriptor = Type.getReturnType(methodInsn.desc).getDescriptor();
            AbstractInsnNode next = insn.getNext();
            while (next != null && next.getOpcode() == -1) next = next.getNext();
            if (next instanceof TypeInsnNode typeInsn && typeInsn.getOpcode() == Opcodes.CHECKCAST) {
                returnDescriptor = "L" + typeInsn.desc + ";";
            }
            bindings.add(new ExtractedBody.FakeBinding((String) ldc.cst, methodInsn.name, returnDescriptor));
        }
        return bindings;
    }

    private static @NotNull Map<LabelNode, LabelNode> buildLabelMap(@NotNull InsnList instructions) {
        Map<LabelNode, LabelNode> labelMap = new HashMap<>();
        for (AbstractInsnNode insn : instructions) {
            if (insn instanceof LabelNode label) {
                labelMap.put(label, new LabelNode());
            }
        }
        return labelMap;
    }

    private static @NotNull InsnList cloneInstructions(@NotNull InsnList original, @NotNull Map<LabelNode, LabelNode> labelMap) {
        InsnList cloned = new InsnList();
        for (AbstractInsnNode abstractInsnNode : original) {
            cloned.add(abstractInsnNode.clone(labelMap));
        }
        return cloned;
    }

    private static @NotNull List<TryCatchBlockNode> cloneTryCatchBlocks(@NotNull List<TryCatchBlockNode> original, @NotNull Map<LabelNode, LabelNode> labelMap) {
        List<TryCatchBlockNode> cloned = new ArrayList<>(original.size());
        for (TryCatchBlockNode tcb : original) {
            LabelNode start = labelMap.getOrDefault(tcb.start, tcb.start);
            LabelNode end = labelMap.getOrDefault(tcb.end, tcb.end);
            LabelNode handler = labelMap.getOrDefault(tcb.handler, tcb.handler);
            cloned.add(new TryCatchBlockNode(start, end, handler, tcb.type));
        }
        return cloned;
    }

    private static @NotNull List<LocalVariableNode> cloneLocalVariables(@NotNull MethodNode method, @NotNull Map<LabelNode, LabelNode> labelMap) {
        if (method.localVariables == null) return List.of();
        List<LocalVariableNode> cloned = new ArrayList<>(method.localVariables.size());
        for (LocalVariableNode lv : method.localVariables) {
            LabelNode start = labelMap.getOrDefault(lv.start, lv.start);
            LabelNode end = labelMap.getOrDefault(lv.end, lv.end);
            cloned.add(new LocalVariableNode(lv.name, lv.desc, lv.signature, start, end, lv.index));
        }
        return cloned;
    }

    public static boolean isFakeCall(@NotNull MethodInsnNode insn) {
        return FAKES_CLASSES.contains(insn.owner) && insn.name.startsWith("fake") && insn.desc.startsWith(FAKE_DESCRIPTOR);
    }
}
