package dev.lumenlang.lumen.plugin.inject.bytecode;

import dev.lumenlang.lumen.api.inject.Fakes;
import dev.lumenlang.lumen.api.inject.body.InjectableBody;
import org.jetbrains.annotations.NotNull;
import org.objectweb.asm.ClassReader;
import org.objectweb.asm.Opcodes;
import org.objectweb.asm.Type;
import org.objectweb.asm.tree.AbstractInsnNode;
import org.objectweb.asm.tree.ClassNode;
import org.objectweb.asm.tree.InsnList;
import org.objectweb.asm.tree.LabelNode;
import org.objectweb.asm.tree.LdcInsnNode;
import org.objectweb.asm.tree.MethodInsnNode;
import org.objectweb.asm.tree.MethodNode;
import org.objectweb.asm.tree.TypeInsnNode;

import java.io.IOException;
import java.io.InputStream;
import java.io.Serializable;
import java.lang.invoke.SerializedLambda;
import java.lang.reflect.Method;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * Extracts bytecode instructions from an {@link InjectableBody} lambda or method reference.
 *
 * <p>Locates the synthetic lambda method generated by the compiler, reads its instruction list,
 * and identifies all calls to {@link Fakes} methods that need to be replaced with real bindings.
 */
public final class BytecodeExtractor {

    private static final String FAKES_INTERNAL = Type.getInternalName(Fakes.class);
    private static final Set<String> FAKES_CLASSES = Set.of(FAKES_INTERNAL);
    private static final String FAKE_DESCRIPTOR = "(Ljava/lang/String;)";

    /**
     * Extracts the bytecode body from the given serializable lambda instance.
     *
     * @param body the serializable lambda to extract from (InjectableBody, InjectableExpression, or InjectableCondition)
     * @return the extracted body with instructions and binding metadata
     * @throws IllegalArgumentException if the lambda method cannot be found or read
     */
    public static @NotNull ExtractedBody extract(@NotNull Serializable body) {
        SerializedLambda serialized = serializeLambda(body);
        String declaringClassName = serialized.getImplClass().replace('/', '.');
        String implMethodName = serialized.getImplMethodName();

        Class<?> declaringClass;
        try {
            declaringClass = Class.forName(declaringClassName, false, body.getClass().getClassLoader());
        } catch (ClassNotFoundException e) {
            throw new IllegalArgumentException("Cannot find declaring class: " + declaringClassName, e);
        }

        ClassNode classNode = readClassNode(declaringClass);
        MethodNode target = findMethod(classNode, implMethodName);
        if (target == null) {
            throw new IllegalArgumentException("Could not locate lambda method '" + implMethodName + "' in " + declaringClassName);
        }

        List<ExtractedBody.FakeBinding> fakeBindings = detectFakeBindings(target.instructions);
        InsnList cloned = cloneInstructions(target.instructions);
        String returnDescriptor = Type.getReturnType(target.desc).getDescriptor();

        return new ExtractedBody(cloned, fakeBindings, classNode.name, returnDescriptor, target.maxStack, target.maxLocals);
    }

    /**
     * Extracts bytecode from a named static method in the given class.
     *
     * @param clazz the class containing the method
     * @param methodName the name of the static method to extract
     * @return the extracted body
     * @throws IllegalArgumentException if the method cannot be found
     */
    public static @NotNull ExtractedBody extractMethod(@NotNull Class<?> clazz, @NotNull String methodName) {
        ClassNode classNode = readClassNode(clazz);
        MethodNode target = findMethod(classNode, methodName);
        if (target == null) {
            throw new IllegalArgumentException("Method '" + methodName + "' not found in " + clazz.getName());
        }

        List<ExtractedBody.FakeBinding> fakeBindings = detectFakeBindings(target.instructions);
        InsnList cloned = cloneInstructions(target.instructions);
        String returnDescriptor = Type.getReturnType(target.desc).getDescriptor();

        return new ExtractedBody(cloned, fakeBindings, classNode.name, returnDescriptor, target.maxStack, target.maxLocals);
    }

    private static @NotNull SerializedLambda serializeLambda(@NotNull Serializable lambda) {
        try {
            Method writeReplace = lambda.getClass().getDeclaredMethod("writeReplace");
            writeReplace.setAccessible(true);
            return (SerializedLambda) writeReplace.invoke(lambda);
        } catch (Exception e) {
            throw new IllegalArgumentException("Failed to serialize lambda. Ensure InjectableBody is used as a lambda expression.", e);
        }
    }

    private static MethodNode findMethod(@NotNull ClassNode classNode, @NotNull String methodName) {
        for (MethodNode mn : classNode.methods) {
            if (mn.name.equals(methodName)) return mn;
        }
        return null;
    }

    private static @NotNull ClassNode readClassNode(@NotNull Class<?> clazz) {
        String resourceName = clazz.getName().replace('.', '/') + ".class";
        try (InputStream is = clazz.getClassLoader().getResourceAsStream(resourceName)) {
            if (is == null) {
                throw new IllegalArgumentException("Cannot read class file for " + clazz.getName());
            }
            ClassReader reader = new ClassReader(is);
            ClassNode node = new ClassNode();
            reader.accept(node, 0);
            return node;
        } catch (IOException e) {
            throw new IllegalArgumentException("Failed to read class file for " + clazz.getName(), e);
        }
    }

    private static @NotNull List<ExtractedBody.FakeBinding> detectFakeBindings(@NotNull InsnList instructions) {
        List<ExtractedBody.FakeBinding> bindings = new ArrayList<>();
        for (AbstractInsnNode insn : instructions) {
            if (insn.getType() != AbstractInsnNode.METHOD_INSN) continue;
            MethodInsnNode methodInsn = (MethodInsnNode) insn;
            if (!isFakeCall(methodInsn)) continue;

            AbstractInsnNode prev = insn.getPrevious();
            if (prev instanceof LdcInsnNode ldc && ldc.cst instanceof String bindingName) {
                String returnDescriptor = Type.getReturnType(methodInsn.desc).getDescriptor();
                AbstractInsnNode next = insn.getNext();
                while (next != null && next.getOpcode() == -1) next = next.getNext();
                if (next instanceof TypeInsnNode typeInsn && typeInsn.getOpcode() == Opcodes.CHECKCAST) {
                    returnDescriptor = "L" + typeInsn.desc + ";";
                }
                bindings.add(new ExtractedBody.FakeBinding(bindingName, methodInsn.name, returnDescriptor));
            }
        }
        return bindings;
    }

    private static @NotNull InsnList cloneInstructions(@NotNull InsnList original) {
        Map<LabelNode, LabelNode> labelMap = new HashMap<>();
        for (AbstractInsnNode insn : original) {
            if (insn instanceof LabelNode label) {
                labelMap.put(label, new LabelNode());
            }
        }

        InsnList cloned = new InsnList();
        for (AbstractInsnNode abstractInsnNode : original) {
            cloned.add(abstractInsnNode.clone(labelMap));
        }
        return cloned;
    }

    static boolean isFakeCall(@NotNull MethodInsnNode insn) {
        return FAKES_CLASSES.contains(insn.owner) && insn.name.startsWith("fake") && insn.desc.startsWith(FAKE_DESCRIPTOR);
    }
}
