package net.vansencool.lumen.pipeline.language.tokenization;

/**
 * Classifies the lexical category of a {@link Token} produced by the
 * {@link Tokenizer}.
 *
 * @see Token
 * @see Tokenizer
 */
public enum TokenKind {
    /**
     * An identifier or keyword, including possessives like {@code player's}.
     *
     * <p>
     * This covers any word-like token: variable names, type names, keywords such as
     * {@code var} or {@code if}, and possessive forms where an apostrophe is
     * attached
     * to the word (e.g. {@code player's}).
     */
    IDENT,

    /**
     * A numeric literal consisting of a sequence of digits, optionally containing a
     * decimal point.
     *
     * <p>
     * Both integer literals like {@code 42} and decimal literals like {@code 3.14}
     * are classified as NUMBER tokens.
     */
    NUMBER,

    /**
     * A double-quoted string literal with quotes stripped and escape sequences
     * resolved.
     *
     * <p>
     * The tokenizer removes the surrounding {@code "} characters and processes
     * standard escape sequences before producing this token.
     */
    STRING,

    /**
     * A single non-alphanumeric, non-whitespace character such as {@code >},
     * {@code <},
     * {@code =}, or {@code +}.
     *
     * <p>
     * Each symbol character becomes its own token, allowing the parser to handle
     * operators and punctuation individually.
     */
    SYMBOL,

    /**
     * A token produced outside the normal tokenization path, reserved for special
     * use.
     *
     * <p>
     * Raw tokens are not generated by the standard {@link Tokenizer} but may be
     * injected programmatically for advanced pattern matching or internal
     * processing.
     */
    RAW
}
