name: Build and Publish

on:
  push:
    branches:
      - '**'
    paths:
      - 'api/**'
      - 'pipeline/**'
      - 'plugin/**'
      - 'debug/**'
      - 'build.gradle'
      - 'settings.gradle'
      - 'gradle.properties'
      - 'gradle/**'
      - 'gradlew'
      - 'gradlew.bat'
      - '.github/workflows/build_and_publish.yml'

jobs:
  buildandpublish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew shadowJar

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: lumen-jar
          path: build/libs/lumen-*.jar
          retention-days: 15

      - name: Publish artifacts
        env:
          PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
        run: |
          HASH=$(echo "${{ github.sha }}" | cut -c1-7)
          VERSION=$(grep "^[[:space:]]*version = " build.gradle | sed "s/.*version = '//" | sed "s/'.*//")
          if [[ "$VERSION" == *"SNAPSHOT"* ]]; then
            BASE_VERSION="${VERSION%-SNAPSHOT}"
            NEW_VERSION="${BASE_VERSION}-dev.${{ github.run_number }}-${HASH}"
          else
            NEW_VERSION="${VERSION}-release.${{ github.run_number }}-${HASH}"
          fi
          sed -i "s/version = '${VERSION}'/version = '${NEW_VERSION}'/" build.gradle
          ./gradlew publishAll
